---
title: "501CE-NONPROFIT-PZ Data Dictionary"
format: html
editor: visual
execute: 
  echo: false
  warning: false
---

```{r echo=FALSE}
library(dplyr)
library(kableExtra)

dd <- readr::read_csv("https://raw.githubusercontent.com/UrbanInstitute/nccstools/main/crosswalks/ds-core/CORE-HRMN-DD.csv?token=GHSAT0AAAAAACGVREUY234CDVH7JBYWKD6AZOBJF6Q")
```

The PZ Version of the harmonized 501(c) Nonprofits data set contains variables common
across both Form 990 and Form 990EZ filings for all other 501(c) organizations. 
This data set includes a larger number of organizations but a smaller number of 
variables than the 501(c) Nonprofit PC data set.

## Data Dictionary

```{r}
both <- data.frame(
  variable_name = c( "RTRN_ID", 
                     "DUP_RTRN_X",
                     "MISSION_NTEE",
                     "GEO_ZIP5" ),
  variable_description = c( "Unique Row ID",
                            "Indicates a Duplicate Return",
                            "IRS NTEE Code",
                            "5 Digit Zip Code" ),
  variable_source = rep( "NCCS", 4 ),
  form_location = rep( NA, 4 ),
  variable_coverage = rep( "1989-2019", 4 ),
  variable_datatype = rep( "character", 4 )
)

dd <- dd %>%
  dplyr::filter( form_scope == "501CE-NONPROFIT-PZ" ) %>% 
  dplyr::select(  
    variable_name,
    variable_description,
    variable_source,
    form_location,
    variable_coverage,
    variable_datatype
    )

dd_combined <- dplyr::bind_rows(  both, dd )

dd_combined %>% 
  knitr::kable( escape=FALSE,
                col.names = c("Variable Name", 
                              "Description",
                              "Variable Source",
                              "Location Code",
                              "Coverage",
                              "Data Type") ) %>%
  kableExtra::kable_styling( full_width = FALSE ) %>% 
  column_spec( column = c( 2, 4), width_min = "10cm" ) %>% 
  column_spec( column = 5, width_min = "5cm" )
```

